os: linux
dist: bionic
language: cpp
python: 3.8

# Compiler selection
compiler:
- gcc
- clang

install:
  - mkdir deps
  - cd deps
  - ../scripts/install-catch2.sh
  - cd ../
  - pip3 install --user -r requirements.txt
  - pip3 install --user .

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - colorlib_gen -re --target "cpp" --enum-name "cl_colors" --function-name "cl_map" --config "./example_conf.yaml" "./tests/colorlib_map.hpp"
  - cd ${TRAVIS_BUILD_DIR}/tests
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest
